---
- hosts: db_bastian
  become: yes
  connection: ssh
  gather_facts: no
  vars_files:
   - vars.yml
  
  tasks:
  - name: Checking for Archive tables
    find:
      paths:            "{{ find_where }}"
      patterns:         "{{ find_what }}"
      recurse:          "yes"
      file_type:        "file"
    register: find_result

  # Printing the results
  - name: print find_result
    debug: var=find_result

  # Copy only the archive files to a common folder 
  - name: Copy files to the archive folder
    copy:
      src: /var/logs/ARCHIVE_*
      dest: /user/home/archives
    register: copy_result

  # Backup the archive files on the folder to s3 bucket
   - name: copy to aws s3 bucket
     when: copy_result|succeeded
     command: aws s3 sync /user/home/archives s3://barrymaiyo
     register: s3copy_result
  
  # Delete the files on the archive folder after s3 upload     
  - name: Delete the archive tables
    when: s3copy_result|succeeded
    file:
     path: "{{ item.path }}"
     state: absent
    with_items: "{{ find_result.files }}"
    register: delete_complete

  # Send email notification if the process is successful
  - name: Send default notification email via SNS
    sns:
      msg: 'Process has completed.'
      subject: Process complete!
      topic: deploy
      region: {{ aws_region }}
      when: delete_complete|succeeded

  # Send email notification if the process fails
  - name: Send default notification email via SNS
    sns:
      msg: 'Process has Failed.'
      subject: Process Aborted!
      topic: deploy
      region: {{ aws_region }}
      when: delete_complete|failed
  
   
